Database:
  host: localhost
  user: 'use environment variable'
  password: 'use environment variable'
  name: picstrata
FileSystem:
  type: local
  localFileSystem:
    root: /var/lib/picstrata/libraries
  s3FileSystem:
    accessKeyId: 'use environment variable'
    secretAccessKey: 'use environment variable'
    bucket: picstrata-localdev
Queue:
  type: beanstalkd
  host: localhost
TimeZoneDb:
  apiKey: 'use environment variable'