Database:
  host: PST_DATABASE_HOST
  user: PST_DATABASE_USER
  password: PST_DATABASE_PASSWORD
  name: PST_DATABASE_NAME
FileSystem:
  type: PST_FILE_SYSTEM_TYPE
  localFileSystem:
    root: PST_LOCAL_FILE_SYSTEM_ROOT
  s3FileSystem:
    accessKeyId: PST_S3_ACCESS_KEY_ID
    secretAccessKey: PST_S3_SECRET_ACCESS_KEY
    bucket: PST_S3_FILE_SYSTEM_BUCKET
Queue:
  type: PST_QUEUE_TYPE
  host: PST_QUEUE_HOST
ApiKeys:
  key1: PST_API_KEY_1
  key2: PST_API_KEY_2