Database:
  host: localhost
  user: reimasuser
  password: =eJ+MVukg2#L%55e
  name: reimas
FileSystem:
  type: local
  localFileSystem:
    root: ./libraries
  s3FileSystem:
    bucket: reimas-localdev