Database:
  host: 'use environment variable'
  user: 'use environment variable'
  password: 'use environment variable'
  name: picstrata
FileSystem:
  type: local
  localFileSystem:
    root: /var/lib/picstrata/libraries
  s3FileSystem:
    bucket: 'use environment variable'
MessageQueue:
  url: 'use environment variable'
ApiKeys:
  key1: 'use environment variable'
  key2: 'use environment variable'